CMakeLists.txt
cmake/bitcoin-config.h.in
src/CMakeLists.txt

This is a first PR into a staging branch as suggested in https://github.com/bitcoin/bitcoin/pull/27060#issuecomment-1431798320.
This PR:
1. Establishes the minimum required CMake [version](https://gitlab.kitware.com/cmake/community/-/wikis/CMake-Versions-on-Linux-Distros). As it looks non-productive to support Ubuntu Bionic as a build platform, version [3.13](https://cmake.org/cmake/help/latest/release/3.13.html) has been chosen.
2. Creates a `bitcoin-config.h` header in the build tree.
To configure a build system, one can run in their local repo root:
- on Linux / *BSD / macOS:
```sh
cmake -S . -B  build
```
- on Windows:
```cmd
cmake -G "Visual Studio 17 2022" -A x64 -S . -B build
```
To re-configure, it is recommended to use the clean build tree, for example:
```sh
rm -rf build
```
For …

build: Add CMake-based build system (1 of N)

---

CMakeLists.txt
cmake/bitcoin-config.h.in
cmake/crc32c.cmake
cmake/introspection.cmake
cmake/leveldb.cmake
cmake/module/CheckSourceCompilesAndLinks.cmake

The parent PR: https://github.com/bitcoin/bitcoin/pull/25797.
The previous PR in the staging branch: https://github.com/hebasto/bitcoin/pull/5.
This PR details:
1. Added project-wide system introspection.
| Autoconf macro | Symbols in `bitcoin-config.h` | CMake implementation |
|---|---|---|
| [`AC_INIT`](https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/autoconf.html#Initializing-configure) | `PACKAGE_NAME` `PACKAGE_TARNAME` `PACKAGE_VERSION` `PACKAGE_STRING` `PACKAGE_BUGREPORT` `PACKAGE_URL` | Done in https://github.com/hebasto/bitcoin/pull/5, except for `PACKAGE_TARNAME` and `PACKAGE_STRING`, which are not currently used |
| [`AX_CXX_COMPILE_STDCXX`](https://www.gnu.org/software/autoconf-archive/ax_cxx_compile_stdcxx.html) | `HAVE_CXX17` `HAVE_CXX20` | CMake uses …

build: Add CMake-based build system (2 of N) 

---

CMakeLists.txt
cmake/introspection.cmake
cmake/minisketch.cmake
cmake/module/AddBoostIfNeeded.cmake
cmake/module/AddLibeventIfNeeded.cmake
cmake/module/AddThreadsIfNeeded.cmake
cmake/module/CheckStdFilesystem.cmake
cmake/secp256k1.cmake
src/CMakeLists.txt
src/crypto/CMakeLists.txt
src/univalue/CMakeLists.txt
src/util/CMakeLists.txt

The parent PR: https://github.com/bitcoin/bitcoin/pull/25797.
The previous PRs in the staging branch: https://github.com/hebasto/bitcoin/pull/5, https://github.com/hebasto/bitcoin/pull/6.
This PR adds the `bitcoind` build target with its dependencies.
To get comparable binaries, one can use the following commands:
- with CMake:
```
cmake -S . -B build -DCMAKE_CXX_FLAGS="-g -O2"
cmake --build build
```
- with Autotools:
```
./autogen.sh
./configure --disable-hardening --disable-wallet --disable-zmq --without-miniupnpc --without-natpmp --disable-usdt
make clean
make -C src bitcoind
```
---
**Windows-specific notes for reviewers**
Windows MSVC builds use dependencies provided by the [vcpkg](https://vcpkg.io) package manager. To install them, run:
```cmd
vcpkg --triplet=x64-windows-static …
```

build: Add CMake-based build system (3 of N)

---

cmake/module/AddBoostIfNeeded.cmake
cmake/module/CrossPkgConfig.cmake
cmake/optional.cmake
src/test/compilerbug_tests.cpp
src/wallet/CMakeLists.txt

The parent PR: https://github.com/bitcoin/bitcoin/pull/25797.
The previous PRs in the staging branch: https://github.com/hebasto/bitcoin/pull/5, https://github.com/hebasto/bitcoin/pull/6, https://github.com/hebasto/bitcoin/pull/7, https://github.com/hebasto/bitcoin/pull/10, https://github.com/hebasto/bitcoin/pull/13, https://github.com/hebasto/bitcoin/pull/15.
This PR consists of fixups only to make reviewing easier :)

build: Add CMake-based build system (7 of N)

---

CMakeLists.txt
cmake/optional.cmake

The parent PR: https://github.com/bitcoin/bitcoin/pull/25797.
The previous PRs in the staging branch: https://github.com/hebasto/bitcoin/pull/5, https://github.com/hebasto/bitcoin/pull/6, https://github.com/hebasto/bitcoin/pull/7, https://github.com/hebasto/bitcoin/pull/10, https://github.com/hebasto/bitcoin/pull/13, https://github.com/hebasto/bitcoin/pull/15, https://github.com/hebasto/bitcoin/pull/17, https://github.com/hebasto/bitcoin/pull/18.
This PR consists of fixups related to using [Ccache](https://ccache.dev/) in MSVC builds.

build: Add CMake-based build system (9 of N)

---

CMakeLists.txt
cmake/leveldb.cmake
cmake/minisketch.cmake
cmake/secp256k1.cmake

This PR follows the master branch approach and amends the previous commits.
Subtrees are treated separately from our code.
Also please refer to:
- https://github.com/hebasto/bitcoin/blob/953d302a242381ae13112ea42f87d57e6e796147/build_msvc/libleveldb/libleveldb.vcxproj#L54
- https://github.com/hebasto/bitcoin/blob/953d302a242381ae13112ea42f87d57e6e796147/build_msvc/libminisketch/libminisketch.vcxproj#L31
- https://github.com/hebasto/bitcoin/blob/953d302a242381ae13112ea42f87d57e6e796147/build_msvc/libsecp256k1/libsecp256k1.vcxproj#L20
- https://github.com/hebasto/bitcoin/blob/953d302a242381ae13112ea42f87d57e6e796147/build_msvc/common.init.vcxproj.in#L91-L93
- and https://github.com/bitcoin/bitcoin/pull/28798
All warning suppressions are documented,

cmake: Silent MSVC warnings

---

CMakeLists.txt

Here are the compiler definitions for MSVC release builds:
- in the master branch:
```
/D _CONSOLE 
/D _CRT_SECURE_NO_WARNINGS 
/D HAVE_CONFIG_H 
/D NOMINMAX 
/D _SILENCE_CXX17_CODECVT_HEADER_DEPRECATION_WARNING 
/D _UNICODE
/D UNICODE 
/D WIN32 
/D _WIN32_IE=0x0501 
/D WIN32_LEAN_AND_MEAN
/D _WIN32_WINNT=0x0601 
```
- in the staging branch:
```
/D _CRT_SECURE_NO_WARNINGS 
/D HAVE_CONFIG_H 
/D _MBCS 
/D NOMINMAX 
/D _SILENCE_CXX17_CODECVT_HEADER_DEPRECATION_WARNING 
/D WIN32 
/D _WIN32_IE=0x0501 
/D WIN32_LEAN_AND_MEAN 
/D _WIN32_WINNT=0x0601 
/D _WINDOWS
```
The diff is:
```diff
-/D _CONSOLE
/D _CRT_SECURE_NO_WARNINGS
/D HAVE_CONFIG_H
+/D _MBCS
/D NOMINMAX
/D _SILENCE_CXX17_CODECVT_HEADER_DEPRECATION_WARNING
-/D _UNICODE
-/D UNICODE
/D WIN32
/D _WIN32_IE=0x0501
/D WIN32_LEAN_AND_MEAN
/D …
```

cmake: Enable Unicode support for MSVC

---

src/CMakeLists.txt
src/bench/CMakeLists.txt
src/test/CMakeLists.txt
src/test/util/CMakeLists.txt
src/util/CMakeLists.txt
src/zmq/CMakeLists.txt

Additionally, this PR fixes "ld: warning: ignoring duplicate libraries" on macOS:
```
[....] Linking CXX executable test_bitcoin
ld: warning: ignoring duplicate libraries: '../../libleveldb.a', '../libbitcoin_common.a', '../univalue/libunivalue.a', '../util/libbitcoin_util.a'
```
```
[....] Linking CXX executable bench_bitcoin
ld: warning: ignoring duplicate libraries: '../../libleveldb.a', '../univalue/libunivalue.a', '../wallet/libbitcoin_wallet.a'
```
The third [commit](https://github.com/hebasto/bitcoin/pull/34/commits/aaf50aced37909c9abf8605e928a5fb1eaa840f0) makes the `bitcoin_wallet` library a direct dependency of `bitcoind` rather `bitcoin_node`, that is outlined in  https://github.com/bitcoin/bitcoin/blob/master/doc/design/libraries.md.

cmake: Avoid overlinking

---

.github/workflows/cmake.yml
vcpkg.json

The new vcpkg manifest file has the same baseline as the one in the master branch. [Additionally](https://learn.microsoft.com/en-us/vcpkg/reference/vcpkg-json), added the `$schema` field and removed the `name` and `version-string` optional fields.
Also added the "Win64 native, VS 2022, built-in tools" CI job, which is modeled after the default build routine for the average Windows user.
The new Windows build documentation has been suggested in https://gist.github.com/hebasto/32c77c0cd592d13685437271ac6b79f6.

cmake: Add vcpkg manifest file

---

cmake/introspection.cmake
cmake/module/FindBerkeleyDB.cmake
cmake/optional.cmake
src/wallet/CMakeLists.txt

SQLite:
- Switching to CMake's [`FindSQLite3`](https://cmake.org/cmake/help/latest/module/FindSQLite3.html) module.
Berkeley DB:
- Our `FindBerkeleyDB` module has been rewritten using CMake guides and similar code from the CMake repo.
- It is compiler-agnostic now and properly handles corner cases with Homebrew and vcpkg package managers.

cmake: Rework searching for wallet dependencies

---

cmake/module/CheckSourceCompilesAndLinks.cmake
src/CMakeLists.txt
src/crypto/CMakeLists.txt

Source files of both `bitcoin_crypto` and `bitcoin_consensus` libraries factored out into interface libraries, which allows us to reuse them when compiling with different build options.
That is required to build upcoming shared libraries that, for example, use additional `-DBUILD_BITCOIN_INTERNAL` preprocessor flag.
No behavior change.
Split from https://github.com/hebasto/bitcoin/pull/41.
---
What to test:
1. Absence of behavior change.
2. The minimum supported CMake 3.16.

cmake: Redesign `bitcoin_crypto` and `bitcoin_consensus` libraries

---

CMakeLists.txt

This PR mirrors https://github.com/hebasto/bitcoin/blob/d5e5810bd36f6e899d64a57e9264729b27a9c3f8/configure.ac#L720-L722
The "cmake: Add platform-specific compiler flags" commit is similar to 8f3a6454144b3b7aa70b38d99e79d7391bc9ec05 "cmake: Add platform-specific linker flags". And both those commits will be reordered in the next rebasing PR to be located next to each other.
---
Two fixup commits are required to fix the commit history as at some point the `try_append_cxx_flags` function is used without `include(TryAppendCXXFlags)`.

cmake: Add platform-specific compiler flags

---

.github/workflows/cmake.yml
CMakeLists.txt
cmake/tests.cmake

This PR:
1. Adds a CI job that uses the minimum required CMake 3.16 and tests the `ALLOW_HOST_PACKAGES` depends feature.
2. Fixes tests when Pyrhon is not available.

cmake: Add a native build job on Ubuntu 20.04 + CMake 3.16

---

cmake/module/AddBoostIfNeeded.cmake

This PR mirrors changes from https://github.com/bitcoin/bitcoin/pull/29066.

cmake: Backport bumping minimum required Boost version

---

cmake/module/TestAppendRequiredLibraries.cmake

This PR mirrors changes from https://github.com/bitcoin/bitcoin/pull/29177.

cmake: Backport check whether `-latomic` needed

---

CMakeLists.txt
cmake/module/Maintenance.cmake
contrib/guix/guix-build
contrib/guix/libexec/build.sh
contrib/guix/manifest.scm

Windows and macOS hosts are disabled temporarily as they require GUI for their deploy targets.

cmake: Migrate Guix build scripts to CMake

---

.github/workflows/cmake.yml

I've been working on a branch, which adds Qt stuff to the CMake-based build system.
However, it is possible that the package search code refactoring will be needed. Therefore, I'd like to get these CI tests in the staging branch to avoid any regressions.

cmake, ci: Add 'Test dependency search' CI job

---

.github/workflows/cmake.yml
CMakeLists.txt
cmake/optional_qt.cmake
depends/Makefile
depends/packages/qt.mk
depends/patches/qt/qt.pro
depends/toolchain.cmake.in
src/CMakeLists.txt
src/qt/CMakeLists.txt
src/qt/winshutdownmonitor.h
vcpkg.json

A new configuration option `WITH_GUI` has been added. Its valid values are `AUTO`, `Qt5`, `OFF`.

cmake: Build `bitcoin-qt` executable

---

cmake/module/Maintenance.cmake
contrib/guix/libexec/build.sh
depends/toolchain.cmake.in

Resolves the https://github.com/hebasto/bitcoin/pull/86#pullrequestreview-1847640073.

cmake: Add `bitcoin-qt` to Guix scripts

---

.github/workflows/cmake.yml

This PR amends CI only with two improvements:
1. Fixes deprecation warnings.
2. Fixes the "No space left on device" error.

cmake: Fix CI jobs

---

.github/workflows/cmake.yml
CMakePresets.json

This PR improves the user experience when building on Windows.
As Visual Studio 17 2022 is minimum [required](https://github.com/bitcoin/bitcoin/blob/master/build_msvc/README.md) to build Bitcoin Core, it is safe to [assume](https://cmake.org/cmake/help/latest/generator/Visual%20Studio%2017%202022.html) that CMake version is not older than 3.21. Moreover, the latest VS 17.8.6 ships CMake 3.27.2.

cmake: Add preset for MSVC build

---

.github/workflows/cmake.yml
cmake/optional.cmake

This PR:
1. Improves the user experience when using the `ccache` package installed via [Chocolatey](https://community.chocolatey.org/packages/ccache) on Windows. The new approach is the same as the one currently used in the master branch CI.
2. Also fix caching for debug configurations (see https://github.com/ccache/ccache/wiki/MS-Visual-Studio#usage-with-cmake)
3. Added caching to the "Win64 native" CI job:
- https://github.com/hebasto/bitcoin/actions/runs/7828761172/job/21362637142
(it might be compared with the log for the same branch, but without the first commit: https://github.com/hebasto/bitcoin/actions/runs/7828850714/job/21363047274)

cmake: Improve Ccache usage on Windows

---

CMakeLists.txt
cmake/module/AddWindowsResources.cmake
cmake/module/GenerateSetupNsi.cmake
cmake/module/Maintenance.cmake
contrib/guix/guix-build
contrib/guix/libexec/build.sh
src/CMakeLists.txt
src/qt/CMakeLists.txt

The Windows installer produced by the `deploy` target is named now `bitcoin-win64-setup.exe`, which differs from the master branch where it is `bitcoin-<VERSION>-win64-setup.exe`. I think, it is more consistent as other build artifacts do not have versioned names.
Guix build:
```
x86_64
c8c04ef3b212650b6121231325353fa490a1a0660e2e9964acc5712f16a279ee  guix-build-f56f5b914480/output/dist-archive/bitcoin-f56f5b914480.tar.gz
97d7b8b509576dc649d252b5b1f54148ed46bd7550acb7b2bf52c47acb9b2b16  guix-build-f56f5b914480/output/x86_64-w64-mingw32/SHA256SUMS.part
1df6445ebb26c973fdca643a3547bea2e1640791ef606354a2d0d06795eacbba  guix-build-f56f5b914480/output/x86_64-w64-mingw32/bitcoin-f56f5b914480-win64-debug.zip
3b95cb0c55f946bdc0f5921651444b3b0dae724e39f8e4a8278cbe8ce02dfd62 …
```

cmake: Re-add Windows host to Guix scripts

---

cmake/module/TryAppendCXXFlags.cmake

This PR is a follow-up on https://github.com/hebasto/bitcoin/pull/74.
No need to try a flag in the linker context if it is not supported in the compiler context.
For example, on the staging branch:
```
$ env CC=clang CXX=clang++ cmake -B build
...
-- Performing Test CXX_SUPPORTS__FSTACK_REUSE_NONE
-- Performing Test CXX_SUPPORTS__FSTACK_REUSE_NONE - Failed
CMake Warning at cmake/module/TryAppendCXXFlags.cmake:125 (message):
The -fstack-reuse=none fail(s) to link.
Call Stack (most recent call first):
CMakeLists.txt:310 (try_append_cxx_flags)
...
```

cmake: Follow-up on PR74

---

cmake/leveldb.cmake

This PR split from https://github.com/hebasto/bitcoin/pull/84
It introduces a new `warn_leveldb_interface`, which overrides `-Wconditional-uninitialized` and `-Wsuggest-override` if any.
For MSVC builds, dropped warning suppressions that are provided at the global level.
For example, on the staging branch:
```
$ env CC=clang CXX=clang++ CXXFLAGS="-Wconditional-uninitialized -Wsuggest-override" cmake -B build
$ cmake --build build --target leveldb > /dev/null 
/home/hebasto/git/bitcoin/src/leveldb/db/c.cc:474:17: warning: 'Name' overrides a member function but is not marked 'override' [-Wsuggest-override]
const char* Name() const { return rep_->Name(); }
^
/home/hebasto/git/bitcoin/src/leveldb/db/c.cc:110:15: note: overridden virtual function is here
const char* Name() const override { …
```

cmake: Silent `leveldb`-specific warnings

---

cmake/module/AddThreadsIfNeeded.cmake
src/CMakeLists.txt
src/util/CMakeLists.txt

The `HAVE_THREAD_LOCAL` is not visible in `src/test/util_threadnames_tests.cpp`. It is easy to verify with the diff as follows:
```diff
--- a/src/test/util_threadnames_tests.cpp
+++ b/src/test/util_threadnames_tests.cpp
@@ -55,6 +55,7 @@ std::set<std::string> RenameEnMasse(int num_threads)
BOOST_AUTO_TEST_CASE(util_threadnames_test_rename_threaded)
{
#if !defined(HAVE_THREAD_LOCAL)
+#error
// This test doesn't apply to platforms where we don't have thread_local.
return;
#endif
```
This PR fixes this issue by moving the macro definition to the `core_interface` library.
Split from https://github.com/hebasto/bitcoin/pull/84.

[BUGFIX] cmake: Fix `HAVE_THREAD_LOCAL` macro visibility

---

cmake/leveldb.cmake
cmake/module/AddLibeventIfNeeded.cmake
src/util/CMakeLists.txt

The `MINGW` variable [might](https://cmake.org/cmake/help/latest/variable/MINGW.html) be uninitialized:
> Otherwise, this variable is not set by CMake.
OTOH, the `$<BOOL:string>` generator expression [expects](https://cmake.org/cmake/help/latest/manual/cmake-generator-expressions.7.html#genex:BOOL) a (defined) string as its argument.
This causes "uninitialized variable" warnings enabled by `--warn-uninitialized` CMake's command line option.
This PR resolves this issue (but not all warnings).

cmake: Fix some "uninitialized variable" warnings

---

cmake/tests.cmake
src/univalue/CMakeLists.txt

As it was pointed out by **TheCharlatan** and **fanquake** during the recent offline meeting, since https://github.com/bitcoin/bitcoin/pull/25369, the Univalue unit tests must be included to the `ctest` suit.

cmake: Add UniValue tests to the `ctest` suit

---

.github/workflows/cmake.yml
CMakeLists.txt
CMakePresets.json
cmake/module/AddBoostIfNeeded.cmake
src/randomenv.cpp

The `x64-windows` triplet is the default one when building on Windows. All dependencies are linked dynamically, which is similar to how they are linked on POSIX systems (Linux, macOS) when building without depends.
CI builds both `x64-windows` and `x64-windows-static` triplets. Additionally `dumpbin /imports` output is provided for the `bitcoind.exe` binaries to observe the triplet effect.

cmake, msvc: Allow to build for default `x64-windows` triplet

---

vcpkg.json

The vcpkg package manager build every package from sources. It might be annoying for the user, who is not going to build the GUI, to wait while `qt*` packages are being built.
This PR fixes this. For example, the following invocation:
```
cd build
cmake -S .. --fresh --preset vs2022 -DVCPKG_MANIFEST_NO_DEFAULT_FEATURES=ON -DVCPKG_MANIFEST_FEATURES="wallet;tests"
```
won't build and install `qt*` packages.
---
**Implementation notes**. It seems possible to populate the `VCPKG_MANIFEST_FEATURES` variable on the basis of the actual build option values. However, considering the required integration with our depends, it is not a trivial task and might be considered later.

cmake: Group vcpkg dependencies by features

---

src/test/fuzz/util/CMakeLists.txt

Useful for configuration log readability. Fuzz binary is not to be confused with other binaries.

cmake: Improve test naming

---

.github/workflows/cmake.yml
CMakeLists.txt
cmake/bitcoin-config.h.in
cmake/module/AddBoostIfNeeded.cmake

A new configuration option is `WITH_EXTERNAL_SIGNER`.

cmake: Add external signer support

---

build-aux/m4/bitcoin_qt.m4
build_msvc/bitcoin_config.h.in
src/qt/CMakeLists.txt
src/qt/bitcoin.cpp
src/qt/guiutil.cpp
src/qt/test/test_main.cpp

1. When using CMake, each plugin comes with a C++ stub file that automatically initializes the static plugin. Consequently, any target that links against a plugin has this C++ file added to its `SOURCES`, which makes the removed code redundant and [duplicates](https://github.com/hebasto/bitcoin/pull/103#issuecomment-1971889904) the included plugins. For example, on the staging branch @ 1a976ca427caa9ead411b605e49b673b2a16802c:
```
2024-03-01T10:51:26Z Bitcoin Core version v26.99.0-1a976ca427ca (release build)
2024-03-01T10:51:26Z Qt 5.15.11 (static), plugin=windows (static)
2024-03-01T10:51:26Z Static plugins:
2024-03-01T10:51:26Z  QWindowsIntegrationPlugin, version 331520
2024-03-01T10:51:26Z  QWindowsVistaStylePlugin, version 331520
2024-03-01T10:51:26Z  QWindowsVistaStylePlugin, …
```

cmake: Do not interfere with Qt plugin handling

---

src/univalue/CMakeLists.txt

This PR addresses https://github.com/hebasto/bitcoin/pull/89#pullrequestreview-1918281111.

cmake: Build Univalue tests only when `BUILD_TESTS` are enabled

---

.github/workflows/cmake.yml

Add workaround for Homebrew's python link error.
Similar to https://github.com/bitcoin/bitcoin/pull/29610.

cmake, ci: Fix "macOS 13 native" job

---

.github/workflows/cmake.yml

For the recent two consequential CI runs:
- https://github.com/hebasto/bitcoin/actions/runs/8263699604 and
- https://github.com/hebasto/bitcoin/actions/runs/8264179478
I've noticed a [pure Ccache performance](https://github.com/hebasto/bitcoin/actions/runs/8264179478/job/22607226576) for the "macOS 13 native, x86_64, Xcode 14.3" job:
```
Cacheable calls:     634 / 634 (100.0%)
Hits:                0 / 634 ( 0.00%)
```
This PR sets `CCACHE_COMPILERCHECK=%compiler% -v` for macOS jobs to avoid false cache invalidating.
The other option, i.e., `content`, has been tried as well in my experiments, but it also has cache performance issues.

cmake, ci: Ccache improving in macOS jobs

---

cmake/bitcoin-config.h.in
cmake/introspection.cmake

This PR backports build system changes from https://github.com/bitcoin/bitcoin/pull/29484.

cmake: Backport PR29484 from the master branch

---

depends/toolchain.cmake.in

See discussion in https://github.com/hebasto/bitcoin/pull/118#discussion_r1522005415.
Can be tested in the following ways:
- applying the `-LH` command line option
- using `cmake-gui`
- direct observing of the `CMakeCache.txt` file content

cmake: Add docstrings for options when cross-compiling

---

CMakeLists.txt

Don't pass `-fno-extended-identifiers` to a linker. Was reported by fanquake offline.

cmake: Don't pass `-fno-extended-identifiers` to a linker

---

src/test/fuzz/CMakeLists.txt

I've noticed that a source file was missed somewhere in rebase / sync cycles.

cmake [FIXUP]: Add the missing source file

---

cmake/bitcoin-config.h.in
cmake/introspection.cmake

This PR:
1) Backports changes from https://github.com/bitcoin/bitcoin/pull/27375.
2) Aligns symbol checks with https://github.com/bitcoin/bitcoin/pull/27699.
A possible way to review this PR and the whole symbol check logic is to observe the Autotools vs CMake diff in the `config/bitcoin-config.h`:
```
./autogen.sh
./configure
cmake -B build
diff -u src/config/bitcoin-config.h build/src/config/bitcoin-config.h
```

cmake: Backport changes from the master branch

---

.github/workflows/cmake.yml

The xz-backdoor affects our vcpkg dependencies. So disabling some of them temporarily to unlock the CI.

cmake, ci: Disable qt5 feature temporarily

---

.github/workflows/cmake.yml
contrib/guix/libexec/build.sh
depends/Makefile

There are no reasons to keep the `share` subdirectory in the path to the toolchain file generated by the depends build subsystem.
This topic was discussed  during the call on 2024-04-04.
Required for the following build docs update.

cmake: Drop `share` subdirectory in depends toolchain file path

---

.github/workflows/cmake.yml
vcpkg.json

This is an alternative to https://github.com/hebasto/bitcoin/pull/137, which does not disable GUI for MSVC builds.

cmake, msvc: Pin liblzma version

---

CMakeLists.txt

Fix typos. There should be mere library names, not variable expansion.

cmake: Fix typos

---

CMakeLists.txt

This PR disables CMake [policies](https://cmake.org/cmake/help/latest/manual/cmake-policies.7.html) available in versions newer than 3.22, which means that for any CMake version >= 3.22, its all policies will be set as if version == 3.22.
The [`CMP0141`](https://cmake.org/cmake/help/latest/policy/CMP0141.html) policy is enabled opportunistically, and is used along with `ccache` for MSVC builds.
The user still able to enforce any police they want with [`CMAKE_POLICY_DEFAULT_CMP<NNNN>`](https://cmake.org/cmake/help/latest/variable/CMAKE_POLICY_DEFAULT_CMPNNNN.html) variables.
This topic was discussed during the call on 2024-04-04.

cmake: Pin policies to the only CMake version

---

.github/workflows/cmake.yml

This PR follows the minimum g++-11 requirements from https://github.com/bitcoin/bitcoin/pull/29091:
1. Update gcc version in the "ubuntu-jammy-native" job.
2. Switch the "cross-build" task to the debian::bookworm image, which effectively bumps `x86_64-w64-mingw32-g++-posix` version to 12.2.
This PR should be merged before the next sync/rebase cycle, which is about to happen.

cmake, ci: Ensure minimum supported g++ version in CI jobs

---

CMakeLists.txt

Remove trailing space to make the linter happy.

cmake: Fix white space linter warning

---

cmake/bitcoin-config.h.in
cmake/introspection.cmake

Backport changes from https://github.com/bitcoin/bitcoin/pull/29081.

cmake: Backport changes from PR29081

---

cmake/module/TestAppendRequiredLibraries.cmake

Backport changes from https://github.com/bitcoin/bitcoin/pull/29859.

cmake: Backport changes from PR29859

---

src/test/CMakeLists.txt

Required in `src/test/raii_event_tests.cpp`.
Otherwise, compiling on illumos (SunOS) fails:
```
/export/home/hebasto/git/bitcoin/src/test/raii_event_tests.cpp:5:10: fatal error: event2/event.h: No such file or directory
5 | #include <event2/event.h>
|          ^~~~~~~~~~~~~~~~
compilation terminated.
```
UPD. The same issue happens on macOS Monterey 12.7.4 (Intel).

cmake: Add missed library for `test_bitcoin`

---

cmake/optional.cmake

Please, refer to `pkg_check_modules` signature: https://cmake.org/cmake/help/latest/module/FindPkgConfig.html#command:pkg_check_modules

cmake: Fix `libqrencode` optional package support

---

.github/workflows/cmake.yml

See https://github.com/bitcoin/bitcoin/pull/29165.

cmake, ci: Bump clang version to 15

---

CMakeLists.txt
cmake/module/Maintenance.cmake
depends/Makefile
depends/toolchain.cmake.in

This PR ports https://github.com/bitcoin/bitcoin/pull/29890 and fixes cross-compiling for macOS been broken since the recent sync/rebase [PR](https://github.com/hebasto/bitcoin/pull/179).

cmake: Port PR29890 from the master branch

---

CMakeLists.txt
doc/CMakeLists.txt
doc/Doxyfile.in
doc/developer-notes.md

Same as `make docs` in the master branch.

cmake: Add `docs` build target

---

src/crypto/CMakeLists.txt

Avoid using source-specific compile options. They hard to reason about and error-prone when combining with target-specific compile options.
The resulted build logic effectively mirrors the master branch's one.
Required for https://github.com/hebasto/bitcoin/pull/157.
Similar to https://github.com/hebasto/bitcoin/pull/171.

cmake: Amend `bitcoin_crypto` static library

---

cmake/crc32c.cmake

Avoid using source-specific compile options. They are hard to reason about and error-prone when combining with target-specific compile options.
The resulted build logic effectively mirrors the master branch's one.
Required for https://github.com/hebasto/bitcoin/pull/157.

cmake: Amend `crc32c` static library

---

.github/workflows/cmake.yml
CMakeLists.txt
CMakePresets.json
cmake/introspection.cmake
cmake/module/FindBerkeleyDB.cmake
cmake/optional.cmake
cmake/optional_qt.cmake

This PR is a continuation of https://github.com/hebasto/bitcoin/pull/161, https://github.com/hebasto/bitcoin/pull/162 and https://github.com/hebasto/bitcoin/pull/164 and tackles with the `WITH_QRENCODE`  options.
It becomes enabled when building GUI with the default value `ON`.

cmake: Switch from tri-state options to boolean. Stage FOUR

---

src/CMakeLists.txt
src/test/CMakeLists.txt
src/util/CMakeLists.txt

This PR ports https://github.com/bitcoin/bitcoin/pull/29904 after the recent sync/rebase [PR](https://github.com/hebasto/bitcoin/pull/179).

cmake: Port PR29904 from the master branch

---

CMakeLists.txt
src/test/validation_chainstate_tests.cpp

Same as on the master branch: https://github.com/hebasto/bitcoin/blob/99d7538cdb2a0ab7a7a2116cd5f33b95fc52b00e/build_msvc/common.init.vcxproj.in#L64
The first commit has been pulled from https://github.com/bitcoin/bitcoin/pull/30026.

cmake: Enable additional security checks for MSVC

---

doc/build-freebsd.md
doc/build-osx.md
doc/build-windows-msvc.md

This PR amends build docs according the discussion in https://github.com/hebasto/bitcoin/pull/167 where there were agreed to use modern cmake invocations.
Simplifies https://github.com/hebasto/bitcoin/pull/173 and https://github.com/hebasto/bitcoin/pull/177.

cmake, doc: Modernize cmake invocations

---

src/test/fuzz/CMakeLists.txt

This PR ports https://github.com/bitcoin/bitcoin/pull/30031 after the recent sync/rebase [PR](https://github.com/hebasto/bitcoin/pull/186).

cmake: Port PR30031 from the master branch

---

.github/workflows/cmake.yml
CMakeLists.txt

This PR ports https://github.com/bitcoin/bitcoin/pull/25972 after the recent sync/rebase [PR](https://github.com/hebasto/bitcoin/pull/186).

cmake: Port PR25972 from the master branch

---

cmake/module/FindQt5.cmake

Mark `Qt5*_DIR` cache variables as advanced to hide them in the GUI and avoid clutter.
See https://github.com/hebasto/bitcoin/issues/194.

cmake: Mark `Qt5*_DIR` cache variables as advanced 

---

vcpkg.json

For more details, see https://github.com/bitcoin/bitcoin/issues/30096.

cmake, vcpkg: Pin `libevent` version

---

CMakeLists.txt
cmake/module/Maintenance.cmake
depends/Makefile
depends/funcs.mk
depends/hosts/android.mk
depends/hosts/darwin.mk
depends/hosts/freebsd.mk
depends/hosts/linux.mk
depends/hosts/mingw32.mk
depends/hosts/netbsd.mk
depends/hosts/openbsd.mk
depends/toolchain.cmake.in

As it was [pointed](https://github.com/hebasto/bitcoin/pull/82#discussion_r1534141067) out during today's call, the toolchain file, which is generated by the depends build system, unnecessarily triggers CMake's [cross-compiling](https://cmake.org/cmake/help/latest/variable/CMAKE_CROSSCOMPILING.html) mode by setting the [`CMAKE_SYSTEM_NAME`](https://cmake.org/cmake/help/latest/variable/CMAKE_SYSTEM_NAME.html) variable even the host and build systems coincides.
That behavior deviates from the current master branch and potentially might have unwanted/unexpected side effects.
This PR fixes this issue.
All Guix builds remain cross-compiling.

[FIXUP] cmake: Do not trigger cross-compiling unnecessarily

---

cmake/bitcoin-config.h.in
src/crypto/sha256.cpp
src/httpserver.cpp
src/qt/qrimagewidget.cpp
src/qt/receiverequestdialog.cpp
src/test/util_threadnames_tests.cpp
test/lint/test_runner/src/main.rs

The linter has been adjusted to consider CMake-specific `bitcoin-config.h.in` file.
Linter warnings have been fixed.
Can be tested by running linters [locally](https://github.com/bitcoin/bitcoin/tree/master/test/lint#running-locally).

cmake, lint: Adjust `lint_includes_build_config`

---

src/CMakeLists.txt

This PR ports https://github.com/bitcoin/bitcoin/pull/29494 after the recent sync/rebase [PR](https://github.com/hebasto/bitcoin/pull/202).

cmake: Port PR29494 from the master branch

---

.github/workflows/cmake.yml

This change fixes CI jobs as the `miniupnpc` source archive is not available neither at https://miniupnp.tuxfamily.org nor at https://bitcoincore.org/depends-sources at this moment.
It could be reverted back after https://github.com/bitcoin/bitcoin/pull/30151 or uploading  the source archive to the https://bitcoincore.org.

cmake, ci: Skip `miniupnpc` package in depends

---

cmake/crc32c.cmake
cmake/secp256k1.cmake

Fixes the second point from https://github.com/bitcoin/bitcoin/pull/29790#issuecomment-2121349899:
>    2. Missed disabling `EXPORT_COMPILE_COMMANDS` property for targets in the `crc32c` subtree.

cmake: Disable `EXPORT_COMPILE_COMMANDS` for all subtree targets

---

ci/test/00_setup_env.sh
ci/test/03_test_script.sh

Fixes the first point from https://github.com/bitcoin/bitcoin/pull/29790#issuecomment-2121349899:
>    1. `Cannot open mapping file '/ci_container_base/ci/scratch/build-/contrib/devtools/iwyu/bitcoin.core.imp': No such file or directory.`

cmake: Fix "tidy" CI job

---

CMakeLists.txt
cmake/module/AddThreadsIfNeeded.cmake

This PR ports https://github.com/bitcoin/bitcoin/pull/30137.
The `target_compile_definitions` command is to be deleted during the next sync/rebase round. Such an early porting is needed for https://github.com/hebasto/bitcoin/pull/93 in order to delete the only non-config related generator expression from the compile definitions, which simplifies the summary code a lot.
Effectively, this commit has been split from https://github.com/hebasto/bitcoin/pull/93.

cmake: Port PR30137 from the master branch

---

CMakeLists.txt

During testing https://github.com/hebasto/bitcoin/pull/93, a few issues were [noticed](https://github.com/hebasto/bitcoin/pull/93#issuecomment-2126748162):
- > `-mbranch-protection=bti` shouldn't be in C flags
The other change simplifies the summary code in https://github.com/hebasto/bitcoin/pull/93.

cmake: Fix hardening flags

---

.github/workflows/cmake.yml
cmake/module/AddBoostIfNeeded.cmake

This PR mirrors the master branch behaviour.

cmake: Add `BOOST_NO_CXX98_FUNCTION_BASE` definition when needed

---

.github/workflows/ci.yml
.github/workflows/cmake.yml

GitHub Actions have deployed a new Windows image version [`20240603.1`](https://github.com/actions/runner-images) recently.
Unfortunately it breaks many things:
1. MSVC built-in vcpkg installation fails to build the `pkgconf` package.
2. DLL versioning has been [broken](https://github.com/actions/runner-images/issues/10004), which makes impossible to run / test dynamically linked binaries.
This PR fixes all the mentioned issues.

cmake, ci: Fix native Windows jobs

---

CMakeLists.txt
cmake/cov_tool_wrapper.sh.in
cmake/script/Coverage.cmake
cmake/script/CoverageFuzz.cmake
cmake/script/CoverageInclude.cmake.in
doc/developer-notes.md

Using separated scripts provides additional flexibility as there is no need to specify coverage report specific options during the build configuration stage.
Examples of usage on Ubuntu 24.04 with [LCOV v2.0](https://packages.ubuntu.com/noble/lcov):
- total coverage:
```
$ cmake -B build -DCMAKE_BUILD_TYPE=Coverage -DCMAKE_CXX_FLAGS="-fprofile-update=atomic"
$ cmake --build build
$ cmake -DLCOV_OPTS="--ignore-errors mismatch" -P build/Coverage.cmake
$ cmake \
-DJOBS=$(nproc) \
-DEXTENDED_FUNCTIONAL_TESTS=ON \
-DLCOV_OPTS="--rc branch_coverage=1 --ignore-errors mismatch" \
-P build/Coverage.cmake
```
- fuzz coverage:
```
$ cmake -B build -DCMAKE_BUILD_TYPE=Coverage -DCMAKE_CXX_FLAGS="-fprofile-update=atomic" -DBUILD_FUZZ_BINARY=ON
$ cmake --build build
$ cmake \ …
```

cmake: Add `Coverage` script

---

cmake/module/AddBoostIfNeeded.cmake

The first commit was requested offline.
The second commit speeds up configuration.

cmake: Improve Boost checks

---

src/qt/CMakeLists.txt

The suggested steps to test:
1. Run Autotools' `make translate`:
```
$ ./autogen.sh && ./configure --with-incompatible-bdb
$ make -C src translate
```
2. Commit changes.
3. Then build CMake's `translate` target:
```
$ cmake -B build -DBUILD_GUI=ON -DWITH_BDB=ON
$ cmake --build build -t translate
```
No new changes must be introduced.

cmake: Implement `translate` target

---

.github/workflows/cmake.yml
CMakeLists.txt

See https://github.com/bitcoin/bitcoin/pull/30312.
To test this PR, please cherry-pick a commit from https://github.com/bitcoin/bitcoin/pull/30312 and do Guix build.

cmake: Do not add rpath information to compiled executables

---

CMakeLists.txt

Descriptions and the comment have been aligned with https://github.com/bitcoin-core/secp256k1/pull/1546.
Closes https://github.com/hebasto/bitcoin/issues/239.

[FIXUP] cmake: Improve description and document `APPEND_*FLAGS`

---

.github/workflows/cmake.yml
CMakeLists.txt
src/CMakeLists.txt

This is a follow-up of https://github.com/bitcoin/bitcoin/pull/30312 and https://github.com/hebasto/bitcoin/pull/236.
On staging branch @ 8b80c1a3f80509f6c07f24d91176042885961ea5:
```
$ cmake -B build -DBUILD_UTIL_CHAINSTATE=ON -DBUILD_SHARED_LIBS=ON
$ cmake --build build -t bitcoin-chainstate
$ ./build/src/bitcoin-chainstate
./build/src/bitcoin-chainstate: error while loading shared libraries: libbitcoinkernel.so: cannot open shared object file: No such file or directory
```
This PR fixes this issue and adds a new CI job to check it.

cmake: Keep RPATH for the `bitcoin-chainstate` target in the build tree

---

src/kernel/CMakeLists.txt

The `-no-undefined` is not a linker flag, rather a Libtool flag, which we do not care about.

cmake: Drop Libtool's option

---

CMakeLists.txt

Otherwise, the policy setting won't get any effect.
See https://cmake.org/cmake/help/latest/policy/CMP0141.html
---
After https://github.com/hebasto/bitcoin/pull/215, the `CMAKE_MSVC_DEBUG_INFORMATION_FORMAT` CMake's abstraction is not used in our code directly, but it is still convenient for the user to be able to use it when configuring the build system from the command line or an IDE.
---
This change can be easily verified on any system (not Windows only) by injecting the following commands:
```cmake
cmake_policy(GET CMP0141 result)
message("${result}")
```

[FIXUP] cmake: Enable CMP0141 policy after `cmake_minimum_required()`

---

CMakeLists.txt
src/qt/CMakeLists.txt
src/test/fuzz/util/CMakeLists.txt

This PR addresses https://github.com/hebasto/bitcoin/pull/192#discussion_r1660817378.
Additionally, fixed a bug in the `translate` target for the `-DBUILD_GUI=ON -DENABLE_WALLET=OFF` configuration.

cmake: Remove log lines from between libsecp's and Core's summaries

---

CMakeLists.txt
cmake/crc32c.cmake
cmake/leveldb.cmake
cmake/minisketch.cmake

This PR addresses  https://github.com/hebasto/bitcoin/issues/241#issuecomment-2205561630:
> That makes me understand that point of these interfaces even less then. Given that the only difference seems to be `warn_interface`, and that not being applied to subtrees currently, would seem to be a bug (at least for leveldb).
Effectively, all C++ subtree targets are using the same build options as the main code.
Closes #241.

cmake: Apply the same build options for C++ subtrees as for main code

---

CMakeLists.txt

This PR addresses https://github.com/hebasto/bitcoin/pull/255#discussion_r1665374443:
> I think this documentation should have been updated? `core_interface` is a requirement for all targets now?

cmake, doc: Fix comment

---

cmake/crc32c.cmake

This PR aligns the code with the master branch: https://github.com/hebasto/bitcoin/blob/d58a3c02883eafa5b2a09afae2b8db9bc14f4dbf/src/Makefile.crc32c.include#L18-L28

cmake: Fix compile definitions for `crc32c` target

---

.github/workflows/cmake.yml

This PR adds `-Wno-error=maybe-uninitialized` for GCC 11.4.
See: https://github.com/bitcoin/bitcoin/pull/29720#issuecomment-2223943553.

cmake, ci: Ignore `-Wmaybe-uninitialized` for GCC 11.4

---

CMakeLists.txt

This PR addresses https://github.com/hebasto/bitcoin/issues/260#issuecomment-2227309231.

[FIXUP] cmake: Add missed `OBJC_OLD_DISPATCH_PROTOTYPES=0`

---

ci/test/00_setup_env_native_nowallet_libbitcoinkernel.sh

This PR ports CI-related changes from https://github.com/bitcoin/bitcoin/pull/30263 and ensures that the minimum required CMake version is available.
Here are CMake versions across all changes:
- pre-PR30263: CMake [3.22.1](https://packages.ubuntu.com/jammy/cmake)
- post-PR30263: CMake [3.18.4](https://packages.debian.org/bullseye/cmake), which is less than the minimum required 3.22
- this PR: CMake [3.28.3](https://packages.ubuntu.com/noble/cmake)

cmake: Port PR30263 from the master branch

---

cmake/module/AddBoostIfNeeded.cmake

This PR silents a developer warning when using >=CMake 3.30.
Closes #257.

cmake: Silent "Policy CMP0167 is not set"

---

cmake/tests.cmake
src/test/compilerbug_tests.cpp

CMake allows to report about skipped tests properly instead of passing dummy test cases. For instance, on Windows:
```
> ctest --build-config Release -R compilerbug
Test project C:/Users/hebasto/source/repos/bitcoin/build
Start 26: compilerbug_tests
1/1 Test #26: compilerbug_tests ................***Skipped   0.02 sec
100% tests passed, 0 tests failed out of 1
Total Test time (real) =   0.04 sec
The following tests did not run:
26 - compilerbug_tests (Skipped)
```
We have 3 such cases:
- `src/test/compilerbug_tests.cpp`
- `src/test/raii_event_tests.cpp`
- `src/test/system_tests.cpp`
This PR handles the first two cases.
Once https://github.com/bitcoin/bitcoin/pull/30454 is merged, the following lines can be deleted: https://github.com/hebasto/bitcoin/blob/9b4aa929b0e84e64472402e594ebb13648b …

cmake: Report skipped tests properly

---

CMakeLists.txt
depends/packages/native_libmultiprocess.mk
depends/toolchain.cmake.in

This PR ports https://github.com/bitcoin/bitcoin/pull/30490 and https://github.com/bitcoin/bitcoin/pull/30513.
The first commit ensures there are no conflicts when applying commits being ported.

cmake: Port PR30490 and PR30513 from the master branch

---

.github/workflows/ci.yml

It was overlooked.
An example of the CI log: https://github.com/hebasto/bitcoin/actions/runs/10117122581/job/27981470109.

cmake, ci: Migrate "test-each-commit" task

---

CMakeLists.txt

Check `-D_FORTIFY_SOURCE` before applying.
This PR follows the master branch behaviour.

cmake: Check `-D_FORTIFY_SOURCE` before applying

---

CMakeLists.txt

The `APPEND_{CPP,C,CXX,LD}FLAGS` flags are now considered when checking compiler/linker flags.
Fixes https://github.com/hebasto/bitcoin/issues/279.

cmake: Allow overriding flags in compiler/linker flag checks

---

cmake/module/TryAppendCXXFlags.cmake

Linker flags should be passed via `CMAKE_REQUIRED_LINK_OPTIONS` rather than `CMAKE_REQUIRED_FLAGS`.
The issue has been reported by [fanquake](https://github.com/fanquake) offline.

cmake: Fix passing linker flags in `TryAppendCXXFlags` module

---

cmake/ccache.cmake

This PR implements the following Autotools functionality: https://github.com/hebasto/bitcoin/blob/f63b2002a1dcb53178626147d61bfd290e63d65b/configure.ac#L1481-L1484
Fixes https://github.com/hebasto/bitcoin/issues/297.

cmake: Implement prefix maps

---

src/qt/CMakeLists.txt
src/qt/bitcoin.cpp
src/qt/test/test_main.cpp

This PR aims to restore [compatibility](https://github.com/bitcoin/bitcoin/pull/30454#issuecomment-2236884983) of the CMake staging branch and https://github.com/bitcoin/bitcoin/pull/30454 with the Autotools-based build system.
On the staging branch @ f63b2002a1dcb53178626147d61bfd290e63d65b:
```
$ make -C depends
$ ./autogen.sh
$ ./configure CONFIG_SITE=$PWD/depends/x86_64-pc-linux-gnu/share/config.site
$ make -C src qt/bitcoin-qt
$ ./src/qt/bitcoin-qt
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
Aborted (core dumped)
```
This PR resolves this issue and adds a TODO comment for the further actions.

cmake: Temporarily revert removal of `Q_IMPORT_PLUGIN` macros

---

CMakeLists.txt
cmake/module/ProcessConfigurations.cmake

This PR makes all compiler/linker flag tests use the following build configuration:
- `CMAKE_BUILD_TYPE` with single-config generator, which means the same configuration during tests and the build.
- the default configuration, which is "RelWithDebInfo", with multi-config generators.
Addresses the issue raised during today's CMake-WG call.

cmake: Use proper build configuration during compiler/linker flag tests

---

doc/build-freebsd.md
doc/build-netbsd.md
doc/build-openbsd.md
doc/build-osx.md
doc/build-unix.md

This PR addresses this [feedback](https://github.com/bitcoin/bitcoin/pull/30454#pullrequestreview-2202007732):
> It seems that the bitcoin-qt `qrencode` dependency default value deviates from the one in autotools. I don't have the qrencode library available in my system and I'm able to compile the gui out of the box through autotools but not through cmake due to the missing dependency. It would be nice to use the same default value for now. And discuss any possible default value change (if needed) in a follow-up.

cmake: Clarify documention regarding libqrencode optional dependency

---

CMakeLists.txt

This PR mirrors the master branch behavior and addresses https://github.com/bitcoin/bitcoin/pull/30454#discussion_r1703899727.

cmake: Drop extraneous `-fvisibility-inlines-hidden`

---

cmake/module/GenerateHeaders.cmake
cmake/module/Maintenance.cmake
cmake/tests.cmake
src/CMakeLists.txt
src/ipc/CMakeLists.txt
src/test/CMakeLists.txt

The current staging branch uses the `PROJECT_{SOURCE,BINARY}_DIR`  and `CMAKE_{SOURCE,BINARY}_DIR`  variables interchangeably.
This PR replaces `CMAKE_{SOURCE,BINARY}_DIR` with `PROJECT_{SOURCE,BINARY}_DIR`, making the code consistent and future-proof.
Addresses https://github.com/bitcoin/bitcoin/pull/30454#discussion_r1703721288.

[FIXUP] cmake: Use `PROJECT_{SOURCE,BINARY}_DIR` consistently

---

.gitignore

It was planned to clean up the `.gitignore` file during the [removal](https://github.com/hebasto/bitcoin/pull/166) of the Autotools and MSVC legacy build systems. However, reviewers requested it [earlier](https://github.com/bitcoin/bitcoin/pull/30454#issuecomment-2267493946).
Therefore, [delivering](https://github.com/bitcoin/bitcoin/pull/30454#issuecomment-2268754162) it now :)

cmake: Ignore build subdirectories within the source directory

---

doc/build-windows.md

Tested on Windows 11 +  WSL + Ubuntu 24.04.
Cleaned up old workaronds (https://github.com/bitcoin/bitcoin/pull/11437 and https://github.com/bitcoin/bitcoin/pull/19408) which no longer seem required.

cmake, doc: Amend Windows build notes

---

cmake/introspection.cmake

Suggested in https://github.com/bitcoin/bitcoin/pull/30454#discussion_r1707417887.

cmake: Simplify introspection module

---

src/test/CMakeLists.txt
src/test/key_tests.cpp

This PR ports a single commit from https://github.com/bitcoin/bitcoin/pull/30051 and amends the `test_bitcoin` target to fix compiling.

cmake: Port PR30051 from the master branch

---

doc/fuzzing.md
src/CMakeLists.txt

A few amendments to the `fuzzing.md`:
1. Removed non-portable $(nproc), mirrors the master branch.
2. Removed stray back slash.
3. Added a linker workaround for macOS.
Also a "TODO" prefix has been added to the comment.

cmake: Amend docs per feedback

---

contrib/guix/libexec/build.sh

Fixes https://github.com/hebasto/bitcoin/issues/297.
CMake uses absolute paths for source files when invoking a compiler. This change makes the resulting Guix binaries location independent.
The resulting behaviour mirrors that of the master branch.
---
NOTE. On the master branch, `HOST_CFLAGS+=" -ffile-prefix-map=${PWD}=."` evaluates to `HOST_CFLAGS+=" -ffile-prefix-map=/bitcoin=."`, which effectively does nothing because there is no such a path among source files being compiled. Binaries appear file path independent because file paths relative to the source directory are used when invoking a compiler.

cmake: Fix prefix maps for Guix builds

---

CMakeLists.txt

In-source builds with CMake are incompatible with Autotools because the `Makefile` files are being overwritten.
This PR provides a clear error message if the user attempts to perform an in-source build.
Unfortunately, this approach does not prevent the source directory from being polluted with a few build artifacts. For more details, please see:
- https://discourse.cmake.org/t/preventing-in-source-builds/881
- https://gitlab.kitware.com/cmake/cmake/-/issues/6672
Resolves https://github.com/hebasto/bitcoin/issues/306.
---
The allowance of in-source builds can be reconsidered after completing the migration from Autotools.

cmake: Forbid in-source builds

---

cmake/module/AddBoostIfNeeded.cmake

Cross-posted from https://github.com/bitcoin/bitcoin/pull/30454#discussion_r1706688706:
> Pretty sure there are two separate bugs here:
> 
>    * The first is that `BOOST_NO_CXX98_FUNCTION_BASE` isn't removed from `CMAKE_REQUIRED_DEFINITIONS` after this check, which means it's incorrectly reused for the check below.
> 
>    * The second is that when `-DWERROR=ON` is used, `-Werror` isn't being passed to the check for the Boost Test header (which also hides the first bug).
This PR addresses the first part (see the commit message for more details).
The second one remains unaddressed for the following reasons:
1. `-DWERROR=ON` (or `--enable-debug` in Autotools) was never used to control passing the `-Werror` flag to checks of any type.
2. In both build systems—Autotools and CMake—we do not …

cmake: Fix `AddBoostIfNeeded` module

---

src/test/README.md

On the master branch, `make check` generates a `foo_tests.log` file for each `foo_tests.cpp`.  These log files are only printed when a test fails. Since no one has raised concerns about the log file [renaming](https://github.com/bitcoin/bitcoin/pull/19385#issuecomment-1078970958) in https://github.com/bitcoin/bitcoin/pull/19385, these files appear to serve no other purpose.
CTest provides its own mechanisms for logging failed tests, making the creation of `foo_tests.log` files unnecessary.
This PR documents these CTest logging mechanisms.
An example of output with a mocked test error:
```
$ ctest --test-dir build -j 16 --output-on-failure
Internal ctest changing into directory: /home/hebasto/git/bitcoin/build
Test project /home/hebasto/git/bitcoin/build
Start  10: amount_tests
Start   6: …
```

cmake, doc: Document log output for failed tests

---

contrib/guix/libexec/build.sh

The [current](https://github.com/bitcoin/bitcoin/pull/30609) Guix's `cmake-minimal` package has version 3.24.2, which has a [bug](https://gitlab.kitware.com/cmake/cmake/-/issues/24601) that causes wrong options for `llvm-strip`.
This PR has exactly the same effect as the [fixed](https://gitlab.kitware.com/cmake/cmake/-/commit/689616785f76acd844fd448c51c5b2a0711aafa2) CMake versions >= 3.27.
Addresses https://github.com/bitcoin/bitcoin/pull/30454#issuecomment-2277722262:
> Had a look at a Guix build. Stripping the macOS binaries is broken:
> 
> ```shell
> -- Installing: /distsrc-base/distsrc-ad2140d4d8cc-arm64-apple-darwin/installed/bitcoin-ad2140d4d8cc/bin/bitcoind
> /root/.guix-profile/bin/llvm-strip: error: unknown argument '-u'
> ```

cmake: Fix `cmake_install` scripts for macOS

---

cmake/module/Maintenance.cmake
src/qt/test/CMakeLists.txt

This PR addresses https://github.com/bitcoin/bitcoin/pull/30454#issuecomment-2288437679:
> Is CMake meant to know about/be able to figure build-time dependencies?
How to test:
- when cross-compiling:
```
$ make -C depends HOST=arm64-apple-darwin
$ cmake -B build --toolchain depends/arm64-apple-darwin/toolchain.cmake
$ cmake --build build -t deploy
```
- on macOS:
```
% cmake -B build -DBUILD_GUI=ON
% cmake --build build -t deploy
```

cmake: Force build-time dependencies for `deploy` target for macOS

---

cmake/module/Maintenance.cmake

It was noted offline:
> I don’t really see why targets, which have dependencies, should, rather than adding those dependencies, instead rely on running the right commands in the right order. That seems like fragile design?
This PR fixes this issue.

cmake: Maintain build-time dependencies for the `check-symbols` and `check-security` targets
